### ISSUE TITLE
页面失效

### ISSUE THREAD

**Issue by attackon1point6** [BDBC-KG-NLP/QA-Survey-CN#7]
请问作者，之前三月份页面还在，现在有些页面失效了，请问是不再公开这些资料了吗？如果页面转移了可以告知一下吗？之前参考过这里的一些资料，收获很大。谢谢作者了！

**Comment by Hillary060** [comment]
@attackon1point6 同学你好，[README.md](https://github.com/BDBC-KG-NLP/QA-Survey-CN/)中文件目录链接已完成更新。

相关应用产品正在系统迁移中，待迁移完成后再开放访问。
非常感谢同学的支持与理解！

**Comment by Hillary060** [comment]
@attackon1point6 同学你好，[README.md](https://github.com/BDBC-KG-NLP/QA-Survey-CN/)中文件目录链接已完成更新。

相关应用产品正在系统迁移中，待迁移完成后再开放访问。
非常感谢同学的支持与理解！

**Comment by attackon1point6** [comment]
> @attackon1point6 同学你好，[README.md](https://github.com/BDBC-KG-NLP/QA-Survey-CN/)中文件目录链接已完成更新。
> 
> 相关应用产品正在系统迁移中，待迁移完成后再开放访问。 非常感谢同学的支持与理解！

非常感谢老师免费提供如此详细的资料，顺着这些资料学到很多！老师们辛苦了！也谢谢老师认真负责，马上就回复了！
